### ISSUE TITLE
傻瓜编辑器的下载链接失效了

### ISSUE THREAD

**Issue by ifeelok92** [chungkwong/fooledit#1]
“点击这里下载傻瓜编辑器”这个链接不能下载，页面404

**Comment by chungkwong** [comment]
已经删除链接，正如目前github首页说明的：“傻瓜编辑器预期在2018年第三季开始公测，在此之前API和所有数据文件格式完全不考虑向后兼容性，稳定性、响应速度和错误处理也不在首要考虑，故切勿用于严肃的场合，为防误用，暂时不会公开完整构建脚本或二进制文件。”同理，虽然已经申请好SSL证书，但现在项目网站的HTTPS故意配置错误，也为降低误入的可能性。
