### ISSUE TITLE
关于此仓库后续的一些问题

### ISSUE THREAD

**Issue by ayu-exorcist** [chungkwong/fooledit#2]
1. 该仓库已有近 1 年未更新，请问还会继续开发吗？
2. 该仓库有提供使用文档或开发文档吗？
3. 有下载链接供使用吗？

**Comment by ayuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu** [comment]
@chungkwong

**Comment by chungkwong** [comment]
1. 短时间内没有计划继续
2. 没有
3. 没有
由于近一年注意力集中在其它项目，而且在Java 9后这仓库中代码的一些具体设计决策失去合理性，即使恢复开发，架构也需要大幅度修改。

**Comment by ayu-exorcist** [comment]
好的，感谢回复。希望之后有机会可以使用该编辑器！
